[package]
name = "pix"
version = "0.13.2"
description = "Pixel / raster image library"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/pix"
homepage = "https://github.com/DougLau/pix"
repository = "https://github.com/DougLau/pix"
readme = "README.md"
keywords = ["pixel", "image", "rgb", "color"]
edition = "2021"
include = [
    "src/**/*", "Cargo.*", "LICENSE-*", "README.md", "CHANGELOG.md",
    "build.rs", "benches/**/*",
]

[features]
default = ["bytemuck"]
bytemuck = ["dep:bytemuck"]

[dependencies]
bytemuck = { version = "1", optional = true }

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "src_over"
harness = false

[[bench]]
name = "rgba_to_rgb"
harness = false
